import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import type { Driver } from '../types';
import { useAssets } from '../context/AssetContext';
import { useAuth } from '../context/AuthContext';
import { useEntity } from '../context/EntityContext';

type Kind = 'ASSET' | 'DRIVER' | 'MAINTENANCE' | 'CLAIM' | 'ROAD_TAX' | 'INSURANCE' | 'INSPECTION' | 'ASSET_ACTION' | 'CONFIGURED_DOCUMENT';
type Job = { id: string; entityId: string; fileName: string; stage: string; progress: number; message: string; recordType?: Kind; recordId?: string; proposedFields: Record<string, string>; confidence: number; sourceReference: string; workflowVersion: number };
type ConfiguredType = { code: string; label: string; fields: string[]; categoryIds: string[] };
const kinds: Kind[] = ['ASSET', 'DRIVER', 'MAINTENANCE', 'CLAIM', 'ROAD_TAX', 'INSURANCE', 'INSPECTION', 'ASSET_ACTION', 'CONFIGURED_DOCUMENT'];
const parse = async <T,>(response: Response): Promise<T> => { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed'); return data as T; };
const toBase64 = (file: File): Promise<string> => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = reject; reader.readAsDataURL(file); });
const mime = (file: File) => file.type || ({ pdf: 'application/pdf', doc: 'application/msword', docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', csv: 'text/csv', txt: 'text/plain', jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png' } as Record<string, string>)[file.name.split('.').pop()?.toLowerCase() || ''] || '';
function ReviewCard({ job, assets, drivers, onApplied }: { job: Job; assets: ReturnType<typeof useAssets>['assets']; drivers: Driver[]; onApplied(): void }) {
  const [kind, setKind] = useState<Kind>(job.recordType || 'ASSET'); const [recordId, setRecordId] = useState(job.recordId || ''); const [fields, setFields] = useState(job.proposedFields); const [busy, setBusy] = useState(false);
  const [configuredTypes, setConfiguredTypes] = useState<ConfiguredType[]>([]);
  useEffect(() => { setKind(job.recordType || 'ASSET'); setRecordId(job.recordId || ''); setFields(job.proposedFields); }, [job.id, job.stage]);
  useEffect(() => { fetch(`/api/asset-documents/types?entityId=${encodeURIComponent(job.entityId)}`).then(response => response.ok ? response.json() as Promise<ConfiguredType[]> : []).then(setConfiguredTypes).catch(() => setConfiguredTypes([])); }, [job.entityId]);
  const targetList = kind === 'DRIVER' ? drivers.filter(item => item.entityId === job.entityId).map(item => ({ id: item.id, label: `${item.name} · ${item.licenseType}` })) : assets.filter(item => item.entityId === job.entityId).map(item => ({ id: item.id, label: `${item.name} · ${item.registrationNumber}` }));
  const selectedAsset = assets.find(item => item.id === recordId);
  const availableTypes = configuredTypes.filter(item => !item.categoryIds.length || !selectedAsset || item.categoryIds.includes(selectedAsset.category));
  const selectCode = (code: string) => { const definition = availableTypes.find(item => item.code === code); setFields(current => ({ ...current, documentCode: code, ...Object.fromEntries((definition?.fields || []).filter(key => !(key in current)).map(key => [key, ''])) })); };
  const accept = async () => { setBusy(true); try { await parse(await fetch(`/api/asset-documents/jobs/${job.id}/accept`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ recordType: kind, recordId, fields }) })); toast.success('Evidence applied to the record history'); onApplied(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not apply evidence'); } finally { setBusy(false); } };
  return <div className="rounded-xl border border-slate-200 bg-white p-5">
    <div className="flex flex-wrap justify-between gap-2"><div><div className="font-bold">{job.fileName}</div><div className="mt-1 text-xs text-slate-500">Workflow v{job.workflowVersion} · {job.stage} · confidence {Math.round(job.confidence * 100)}% · {job.sourceReference || 'No source reference'}</div></div><a className="text-xs font-semibold text-indigo-700 underline" href={`/api/asset-documents/jobs/${job.id}/file`}>Original file</a></div>
    <div className="mt-3 text-sm text-slate-600">{job.message}</div><div className="mt-3 h-1.5 rounded-full bg-slate-100"><div className="h-full bg-indigo-600" style={{ width: `${job.progress}%` }} /></div>
    {['READY_FOR_REVIEW', 'REVIEW_REQUIRED'].includes(job.stage) && <div className="mt-5 border-t pt-4"><div className="text-xs font-bold uppercase text-amber-700">Human confirmation required</div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-600">Event type<select value={kind} onChange={event => setKind(event.target.value as Kind)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm">{kinds.map(item => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></label><label className="text-xs text-slate-600">Target record<select value={recordId} onChange={event => setRecordId(event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="">{['ASSET', 'DRIVER'].includes(kind) ? 'Create a new record' : 'Choose an existing record'}</option>{targetList.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div>
      {kind === 'CONFIGURED_DOCUMENT' && <label className="mt-3 block text-xs text-slate-600">Configured document type<select className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" value={fields.documentCode || ''} onChange={event => selectCode(event.target.value)}><option value="">Select a published type</option>{availableTypes.map(item => <option key={item.code} value={item.code}>{item.label} · {item.code}</option>)}</select></label>}
      <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(fields).filter(([key]) => key !== 'documentCode').map(([key, value]) => <label key={key} className="text-xs text-slate-600">{key}<input value={value} onChange={event => setFields({ ...fields, [key]: event.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></label>)}</div>
      <details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer">Add a missing field</summary><div className="mt-2 flex gap-2"><select id={`field-${job.id}`} className="rounded-lg border px-2 py-1">{['registrationNumber', 'assetName', 'category', 'brand', 'model', 'year', 'driverName', 'licenseNumber', 'licenseType', 'licenseExpiry', 'date', 'expiryDate', 'nextDueDate', 'nextDueHours', 'currentOperatingHours', 'dueDate', 'dueHours', 'actionKind', 'documentCode', 'certificateNumber', 'ownerName', 'ownerEmail', 'cost', 'odometer', 'claimNumber', 'amount', 'insurer', 'description'].filter(key => !(key in fields)).map(key => <option key={key}>{key}</option>)}</select><button onClick={() => { const element = document.getElementById(`field-${job.id}`) as HTMLSelectElement; if (element?.value) setFields({ ...fields, [element.value]: '' }); }} className="rounded-lg border px-2 py-1">Add</button></div></details>
      <button disabled={busy || !kind || kind === 'CONFIGURED_DOCUMENT' && !fields.documentCode} onClick={accept} className="mt-4 rounded-lg bg-indigo-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Confirm and apply to history</button>
    </div>}
  </div>;
}
export function AssetDocuments() {
  const { user } = useAuth(); const { entities, selectedEntityId } = useEntity(); const { assets, refreshAssets } = useAssets();
  const [entityId, setEntityId] = useState(selectedEntityId); const [recordId, setRecordId] = useState(''); const [drivers, setDrivers] = useState<Driver[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [busy, setBusy] = useState(false);
  const refresh = () => { fetch('/api/asset-documents/jobs').then(response => response.json()).then(setJobs).catch(() => undefined); fetch('/api/drivers').then(response => response.json()).then(setDrivers).catch(() => undefined); void refreshAssets(); };
  useEffect(() => { refresh(); const timer = setInterval(refresh, 2500); return () => clearInterval(timer); }, []);
  useEffect(() => { if (selectedEntityId) setEntityId(selectedEntityId); }, [selectedEntityId]);
  const upload = async (files: File[]) => { if (!entityId) return toast.error('Choose an entity first.'); if (!files.length || files.length > 25) return toast.error('Choose 1–25 files.'); setBusy(true); let started = 0; try { for (const file of files) { if (file.size > 10 * 1024 * 1024) throw new Error(`${file.name} exceeds 10 MB.`); await parse(await fetch('/api/asset-documents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entityId, recordId, fileName: file.name, mimeType: mime(file), data: await toBase64(file) }) })); started++; } toast.success(`${started} document job(s) queued`); refresh(); } catch (error) { toast.error(`${started} queued; ${error instanceof Error ? error.message : 'upload failed'}`); } finally { setBusy(false); } };
  const visible = selectedEntityId ? jobs.filter(job => job.entityId === selectedEntityId) : jobs;
  return <div className="mx-auto max-w-7xl space-y-6 p-5 lg:p-8"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-indigo-700">Asset and driver intelligence</div><h1 className="mt-1 text-2xl font-bold">Evidence Queue</h1><p className="mt-1 text-sm text-slate-500">Upload vehicle, driver, maintenance or claim files and photos. AI proposes the event and target; a reviewer confirms before the correct record history changes.</p></div>
    {user?.role !== 'OWNER' && user?.role !== 'EXECUTIVE' && <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="grid gap-3 md:grid-cols-3"><select aria-label="Responsible entity" value={entityId} onChange={event => { setEntityId(event.target.value); setRecordId(''); }} className="rounded-lg border px-3 py-2"><option value="">Select entity</option>{entities.map(entity => <option key={entity.id} value={entity.id}>{entity.displayName}</option>)}</select><select aria-label="Known target" value={recordId} onChange={event => setRecordId(event.target.value)} className="rounded-lg border px-3 py-2"><option value="">Let AI find the record</option>{assets.filter(item => item.entityId === entityId).map(asset => <option key={asset.id} value={asset.id}>{asset.registrationNumber}</option>)}{drivers.filter(item => item.entityId === entityId).map(driver => <option key={driver.id} value={driver.id}>{driver.name}</option>)}</select><label className="cursor-pointer rounded-lg border border-dashed border-indigo-300 px-3 py-2 text-sm font-semibold text-indigo-700">{busy ? 'Uploading…' : 'Choose up to 25 files'}<input type="file" multiple accept=".pdf,.doc,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg" className="hidden" onChange={event => void upload(Array.from(event.target.files || []))} /></label></div><p className="mt-2 text-xs text-slate-500">PDF, DOC/DOCX, XLSX, CSV, text, JPG and PNG · 10 MB per file. Unclear matches stay in review.</p></section>}
    <div className="space-y-3">{visible.slice().reverse().map(job => <ReviewCard key={job.id} job={job} assets={assets} drivers={drivers} onApplied={refresh} />)}{!visible.length && <div className="rounded-xl border border-dashed bg-white p-10 text-center text-slate-500">No asset or driver evidence uploaded yet.</div>}</div>
  </div>;
}
