import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../context/AuthContext';

type RecordRow = { id: string; module: 'CONTRACT' | 'VENDOR' | 'ASSET'; entityId: string; title: string; activity: string; site: string; status: string; agreementStatus?: string; dueDate: string; ownerAssigned: boolean; associatedEntityIds: string[] };
type Overview = { entities: Array<{ id: string; parentId?: string; name: string; activities: string[]; sites: string[] }>; records: RecordRow[]; totals: { contracts: number; vendors: number; assets: number } };
type RecordDetail = { id: string; module: string; title: string; status: string; agreementStatus?: string; activity: string; site: string; ownerAssigned: boolean; evidence: Array<{ label: string; type: string; status: string; uploadedAt: string }>; actions: Array<{ title: string; status: string; dueDate?: string; ownerAssigned: boolean }> };
export function Executive() {
  const { user } = useAuth();
  const [data, setData] = useState<Overview | null>(null); const [entityId, setEntityId] = useState(''); const [activity, setActivity] = useState(''); const [site, setSite] = useState(''); const [module, setModule] = useState('');
  const [detail, setDetail] = useState<RecordDetail | null>(null);
  const openRecord = (item: RecordRow) => { fetch(`/api/executive/record/${item.module}/${item.id}`).then(response => response.json()).then(setDetail); };
  useEffect(() => { if (['EXECUTIVE', 'GROUP_ADMIN'].includes(user?.role || '')) fetch('/api/executive/overview').then(response => response.json()).then(setData); }, [user?.role]);
  const byEntity = useMemo(() => data?.records.filter(item => !entityId || item.entityId === entityId) || [], [data, entityId]);
  const activities = [...new Set(byEntity.map(item => item.activity))].sort();
  const byActivity = byEntity.filter(item => !activity || item.activity === activity);
  const sites = [...new Set(byActivity.map(item => item.site))].sort();
  const rows = byActivity.filter(item => (!site || item.site === site) && (!module || item.module === module));
  if (!['EXECUTIVE', 'GROUP_ADMIN'].includes(user?.role || '')) return <div className="p-8 text-slate-600">Group reporting is available to executives and group administrators.</div>;
  return <div className="mx-auto max-w-7xl space-y-6 p-5 lg:p-8"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-indigo-700">Group intelligence</div><h1 className="mt-1 text-2xl font-bold">Executive Overview</h1><p className="mt-1 text-sm text-slate-500">Drill down from the group to entity, activity, site, module and record. Each record counts once under its primary entity; linked entities are shown without double-counting.</p></div>
    <div className="grid gap-3 sm:grid-cols-3">{[['Contracts', data?.totals.contracts], ['Vendor engagements', data?.totals.vendors], ['Assets', data?.totals.assets]].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5"><div className="text-sm text-slate-500">{label}</div><div className="mt-1 text-3xl font-bold">{value ?? '—'}</div></div>)}</div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Group → entity → activity / site → module → record</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><select aria-label="Entity filter" value={entityId} onChange={event => { setEntityId(event.target.value); setActivity(''); setSite(''); }} className="rounded-lg border px-3 py-2"><option value="">All entities</option>{data?.entities.map(entity => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select><select aria-label="Activity filter" value={activity} onChange={event => { setActivity(event.target.value); setSite(''); }} className="rounded-lg border px-3 py-2"><option value="">All activities</option>{activities.map(item => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Site filter" value={site} onChange={event => setSite(event.target.value)} className="rounded-lg border px-3 py-2"><option value="">All sites</option>{sites.map(item => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Module filter" value={module} onChange={event => setModule(event.target.value)} className="rounded-lg border px-3 py-2"><option value="">All modules</option>{['CONTRACT', 'VENDOR', 'ASSET'].map(item => <option key={item} value={item}>{item}</option>)}</select></div><div className="mt-4 text-sm text-slate-500">{rows.length} unique records in this view</div></section>
    <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Entity', 'Activity / site', 'Module', 'Record', 'Status', 'Agreement', 'Accountable'].map(item => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{rows.map(item => <tr key={`${item.module}:${item.id}`} className="border-b"><td className="px-4 py-3 font-semibold">{data?.entities.find(entity => entity.id === item.entityId)?.name}{item.associatedEntityIds.length > 0 && <div className="text-xs font-normal text-slate-400">+ {item.associatedEntityIds.length} linked entity</div>}</td><td className="px-4 py-3">{item.activity}<div className="text-xs text-slate-500">{item.site}</div></td><td className="px-4 py-3">{item.module}</td><td className="px-4 py-3"><button className="font-semibold text-indigo-700" onClick={() => openRecord(item)}>{item.title}</button></td><td className="px-4 py-3">{item.status}</td><td className={`px-4 py-3 font-semibold ${item.agreementStatus === 'FAILED' ? 'text-red-700' : item.agreementStatus === 'WARNING' ? 'text-amber-700' : 'text-slate-600'}`}>{item.agreementStatus?.replaceAll('_', ' ') || '—'}</td><td className="px-4 py-3">{item.ownerAssigned ? 'Assigned' : 'Unassigned'}</td></tr>)}</tbody></table>{!rows.length && <div className="p-10 text-center text-slate-500">No records match these filters.</div>}</section>
    {detail && <section className="rounded-2xl border border-indigo-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold uppercase text-indigo-700">{detail.module} record</div><h2 className="mt-1 text-xl font-bold">{detail.title}</h2><p className="mt-1 text-sm text-slate-500">{detail.activity} · {detail.site || 'Group-wide'} · {detail.status}{detail.agreementStatus ? ` · Agreement ${detail.agreementStatus.replaceAll('_', ' ')}` : ''} · Owner {detail.ownerAssigned ? 'assigned' : 'unassigned'}</p></div><button onClick={() => setDetail(null)} className="h-fit rounded-lg border px-3 py-1.5 text-sm">Close</button></div><div className="mt-5 grid gap-5 md:grid-cols-2"><div><h3 className="font-bold">Evidence metadata</h3><div className="mt-2 space-y-2">{detail.evidence.map((item, index) => <div key={index} className="rounded-lg bg-slate-50 p-3 text-sm">{item.label} · {item.type} · {item.status}</div>)}{!detail.evidence.length && <div className="text-sm text-slate-500">No evidence recorded.</div>}</div></div><div><h3 className="font-bold">Actions and deadlines</h3><div className="mt-2 space-y-2">{detail.actions.map((item, index) => <div key={index} className="rounded-lg bg-slate-50 p-3 text-sm">{item.title} · {item.status} · {item.dueDate || 'No due date'} · {item.ownerAssigned ? 'Owner assigned' : 'Unassigned'}</div>)}{!detail.actions.length && <div className="text-sm text-slate-500">No actions recorded.</div>}</div></div></div><p className="mt-4 text-xs text-slate-500">Personal identifiers and original documents are omitted from the executive view.</p></section>}
  </div>;
}
