import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { useAuth } from '../context/AuthContext';
import { useEntity } from '../context/EntityContext';

type Module = 'VENDOR' | 'ASSET' | 'DRIVER';
type Job = { id: string; module: Module; entityId: string; fileName: string; status: string; rows: Array<{ number: number; status: string; message?: string; recordId?: string; values: Record<string, string> }> };
const fields: Record<Module, Array<[string, string]>> = { VENDOR: [['legalName', 'Vendor legal name'], ['registrationNumber', 'Registration number'], ['category', 'Vendor category'], ['email', 'Email'], ['phone', 'Phone'], ['address', 'Address'], ['services', 'Services']], ASSET: [['registrationNumberAsset', 'Number plate / asset ID'], ['assetName', 'Asset name'], ['assetCategory', 'Category'], ['brand', 'Brand'], ['model', 'Model'], ['year', 'Year'], ['roadTaxExpiry', 'Road tax expiry'], ['insuranceExpiry', 'Insurance expiry'], ['nextServiceDate', 'Next service']], DRIVER: [['driverName', 'Driver name'], ['licenseNumber', 'Licence number'], ['licenseType', 'Licence class'], ['licenseExpiry', 'Licence expiry'], ['driverPhone', 'Phone']] };
const request = async <T,>(url: string, method = 'GET', body?: unknown): Promise<T> => { const response = await fetch(url, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed'); return data as T; };
export function Intake() {
  const { user } = useAuth(); const { entities, selectedEntityId } = useEntity();
  const [module, setModule] = useState<Module>('VENDOR'); const [entityId, setEntityId] = useState(selectedEntityId); const [content, setContent] = useState(''); const [fileName, setFileName] = useState(''); const [headers, setHeaders] = useState<string[]>([]); const [mapping, setMapping] = useState<Record<string, string>>({}); const [jobs, setJobs] = useState<Job[]>([]); const [busy, setBusy] = useState(false);
  const refresh = () => request<Job[]>('/api/intake/jobs').then(setJobs).catch(() => undefined);
  useEffect(() => { void refresh(); const timer = setInterval(refresh, 2500); return () => clearInterval(timer); }, []);
  useEffect(() => { if (selectedEntityId) setEntityId(selectedEntityId); }, [selectedEntityId]);
  const pick = async (file?: File) => { if (!file) return; if (file.size > 5 * 1024 * 1024) return toast.error('CSV limit is 5 MB.'); const csv = await file.text(); setContent(csv); setFileName(file.name); const first = csv.replace(/^\uFEFF/, '').split(/\r?\n/)[0] || ''; setHeaders(first.match(/(?:"(?:[^"]|"")*"|[^,])+/g)?.map(item => item.replace(/^"|"$/g, '').replaceAll('""', '"').trim()) || []); setMapping({}); };
  const submit = async () => { if (!entityId) return toast.error('Choose an entity.'); if (!content) return toast.error('Choose a CSV file.'); setBusy(true); try { await request('/api/intake/csv', 'POST', { entityId, module, csv: content, fileName, mapping }); setContent(''); setFileName(''); setHeaders([]); refresh(); toast.success('Background CSV processing started'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Upload failed'); } finally { setBusy(false); } };
  const visible = selectedEntityId ? jobs.filter(job => job.entityId === selectedEntityId) : jobs;
  return <div className="mx-auto max-w-7xl space-y-6 p-5 lg:p-8"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-indigo-700">Document-first operations</div><h1 className="mt-1 text-2xl font-bold">Intake Queue</h1><p className="mt-1 text-sm text-slate-500">Upload a sample CSV, map source columns, and monitor background row processing. Originals are retained. Host-to-host SFTP and HTTPS feeds are Phase 2, not represented here as connected.</p></div>
    {user?.role !== 'EXECUTIVE' && user?.role !== 'OWNER' && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">New CSV batch</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><select aria-label="Module" value={module} onChange={event => { setModule(event.target.value as Module); setMapping({}); }} className="rounded-lg border px-3 py-2">{(['VENDOR', 'ASSET', 'DRIVER'] as Module[]).map(value => <option key={value} value={value}>{value}</option>)}</select><select aria-label="Responsible entity" value={entityId} onChange={event => setEntityId(event.target.value)} className="rounded-lg border px-3 py-2"><option value="">Select responsible entity</option>{entities.map(entity => <option key={entity.id} value={entity.id}>{entity.displayName}</option>)}</select><label className="cursor-pointer rounded-lg border border-dashed px-3 py-2 text-sm font-semibold text-indigo-700">{fileName || 'Choose CSV file'}<input type="file" accept=".csv,text/csv" className="hidden" onChange={event => void pick(event.target.files?.[0])} /></label></div>
      {!!headers.length && <div className="mt-5"><h3 className="text-sm font-bold">Column mapping</h3><p className="mt-1 text-xs text-slate-500">Leave a field on automatic detection or select its exact CSV header. Missing required fields enter the review queue.</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields[module].map(([key, label]) => <label key={key} className="text-xs font-semibold text-slate-600">{label}<select value={mapping[key] || ''} onChange={event => setMapping({ ...mapping, [key]: event.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm font-normal"><option value="">Auto-detect</option>{headers.map(header => <option key={header} value={header}>{header}</option>)}</select></label>)}</div></div>}
      <button disabled={busy || !content || !entityId} onClick={submit} className="mt-5 rounded-lg bg-indigo-700 px-4 py-2 font-semibold text-white disabled:opacity-50">Start background processing</button></section>}
    <section className="space-y-3"><h2 className="font-bold">Recent batches</h2>{visible.slice().reverse().map(job => { const created = job.rows.filter(row => row.status === 'CREATED').length; const review = job.rows.filter(row => row.status === 'REVIEW_REQUIRED').length; return <div key={job.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><div><div className="font-bold">{job.fileName}</div><div className="text-sm text-slate-500">{job.module} · {entities.find(entity => entity.id === job.entityId)?.displayName} · {job.rows.length} rows</div></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">{job.status}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-indigo-600" style={{ width: `${Math.round(job.rows.filter(row => !['QUEUED', 'PROCESSING'].includes(row.status)).length / Math.max(1, job.rows.length) * 100)}%` }} /></div><div className="mt-2 text-xs text-slate-500">{created} created · {review} need review · {job.rows.length - created - review} processing/failed</div>{review > 0 && <details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold text-amber-700">Review row exceptions</summary><div className="mt-2 max-h-48 space-y-2 overflow-y-auto">{job.rows.filter(row => row.status === 'REVIEW_REQUIRED').map(row => <div key={row.number} className="rounded-lg bg-amber-50 p-3">Row {row.number}: {row.message}</div>)}</div></details>}</div>; })}{!visible.length && <div className="rounded-xl border border-dashed bg-white p-10 text-center text-slate-500">No CSV batches yet.</div>}</section>
  </div>;
}
