import { useState } from 'react';
import { toast } from 'sonner';
import type { Contract } from '../contractTypes';
import { useContracts } from '../context/ContractContext';
import { useAuth } from '../context/AuthContext';

const field = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';

export function ContractCloseout({ contract }: { contract: Contract }) {
  const { user } = useAuth();
  const { startCloseout, approveCloseout, cancelCloseout, waiveObligation } = useContracts();
  const [kind, setKind] = useState<'TERMINATION' | 'EXPIRY' | 'OTHER'>('TERMINATION');
  const [effectiveDate, setEffectiveDate] = useState('');
  const [reason, setReason] = useState('');
  const [documentId, setDocumentId] = useState('');
  const [waiverReasons, setWaiverReasons] = useState<Record<string, string>>({});
  const [cancelReason, setCancelReason] = useState('');
  const [busy, setBusy] = useState(false);
  const canDecide = user?.role === 'GROUP_ADMIN' || user?.role === 'ENTITY_ADMIN';
  const openObligations = contract.obligations.filter(item => !['COMPLETED', 'WAIVED'].includes(item.status));
  const openPayments = (contract.paymentMilestones || []).filter(item => item.status !== 'WAIVED' && !(item.status === 'SETTLED' && item.reconciliationStatus === 'RECONCILED'));
  const run = async (action: () => Promise<unknown>, message: string) => { setBusy(true); try { await action(); toast.success(message); } catch (error) { toast.error(error instanceof Error ? error.message : 'Close-out action failed.'); } finally { setBusy(false); } };
  return <div className="space-y-5">
    <p className="text-sm text-slate-600">Close-out is a controlled review. It does not erase or automatically complete commitments. Resolve each obligation and payment, or record an explicit audited waiver, before approval.</p>
    {contract.closeout ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><div className="font-bold text-amber-950">{contract.closeout.kind} · {contract.closeout.status}</div><div className="mt-1">Effective {contract.closeout.effectiveDate} · {contract.closeout.reason}</div><div className="mt-1 text-xs text-slate-600">Requested by {contract.closeout.requestedBy}; {contract.closeout.approvedBy ? `closed by ${contract.closeout.approvedBy}` : 'approval pending'}</div></div> : canDecide && ['ACTIVE', 'EXPIRED', 'RENEWAL_REVIEW', 'EXECUTED'].includes(contract.status) ? <div className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><label><span className="text-xs font-bold">Close-out type</span><select className={field} value={kind} onChange={event => setKind(event.target.value as typeof kind)}><option value="TERMINATION">Termination</option><option value="EXPIRY">Expiry</option><option value="OTHER">Other</option></select></label><label><span className="text-xs font-bold">Effective date</span><input type="date" className={field} value={effectiveDate} onChange={event => setEffectiveDate(event.target.value)} /></label><label className="sm:col-span-2"><span className="text-xs font-bold">Reason and authority</span><textarea className={field} rows={2} value={reason} onChange={event => setReason(event.target.value)} placeholder="Explain the termination or close-out decision" /></label><label className="sm:col-span-2"><span className="text-xs font-bold">Signed notice or close-out document</span><select className={field} value={documentId} onChange={event => setDocumentId(event.target.value)}><option value="">None selected</option>{contract.documents.map(item => <option key={item.id} value={item.id}>{item.fileName} · {item.signed ? 'signed' : 'unsigned'} · {item.extractionStatus}</option>)}</select>{kind === 'TERMINATION' && <span className="text-xs text-amber-700">An accepted signed document is required before final termination approval. Upload and review it in Documents.</span>}</label><div className="sm:col-span-2"><button disabled={busy || !effectiveDate || !reason.trim()} onClick={() => run(() => startCloseout(contract.id, { kind, effectiveDate, reason, documentId: documentId || undefined }), 'Close-out review started; open work remains active.')} className="rounded-lg bg-blue-800 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Start close-out review</button></div></div> : null}
    {contract.closeout?.status === 'REVIEW' && <><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-4"><div className="text-xs font-bold uppercase text-slate-500">Unresolved obligations</div><div className="mt-1 text-2xl font-bold">{openObligations.length}</div><p className="mt-1 text-xs text-slate-500">Complete with evidence in Obligations, or waive individually below.</p></div><div className="rounded-xl border p-4"><div className="text-xs font-bold uppercase text-slate-500">Unresolved payments</div><div className="mt-1 text-2xl font-bold">{openPayments.length}</div><p className="mt-1 text-xs text-slate-500">Settle then reconcile, or waive explicitly in Payments.</p></div></div>{openObligations.map(item => <div key={item.id} className="rounded-xl border p-3"><div className="text-sm font-bold">{item.title} · {item.status}</div>{canDecide && <div className="mt-2 flex flex-wrap gap-2"><input className={`${field} flex-1`} value={waiverReasons[item.id] || ''} onChange={event => setWaiverReasons(current => ({ ...current, [item.id]: event.target.value }))} placeholder="Reason for explicit waiver" /><button disabled={busy || !waiverReasons[item.id]?.trim()} onClick={() => run(() => waiveObligation(contract.id, item.id, waiverReasons[item.id]), 'Obligation waiver recorded.')} className="rounded-lg border px-3 py-2 text-xs font-bold text-amber-800 disabled:opacity-40">Waive</button></div>}</div>)}{openPayments.map(item => <div key={item.id} className="rounded-xl border p-3 text-sm">{item.title} · {item.status} {item.status === 'SETTLED' ? `· ${item.reconciliationStatus || 'PENDING'}` : ''}</div>)}{canDecide && <div className="flex flex-wrap gap-2 border-t pt-4"><button disabled={busy || openObligations.length > 0 || openPayments.length > 0} onClick={() => run(() => approveCloseout(contract.id), 'Contract closed with an audit trail.')} className="rounded-lg bg-blue-800 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Approve close-out</button><input className={`${field} max-w-md`} value={cancelReason} onChange={event => setCancelReason(event.target.value)} placeholder="Reason to cancel review" /><button disabled={busy || !cancelReason.trim()} onClick={() => run(() => cancelCloseout(contract.id, cancelReason), 'Close-out review cancelled.')} className="rounded-lg border px-4 py-2 text-sm font-bold text-slate-700 disabled:opacity-40">Cancel review</button></div>}</>}
  </div>;
}
