import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import type { Contract, ContractClause } from '../contractTypes';
import { useContracts } from '../context/ContractContext';

const field = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';
type CurrentTerms = { clauses: ContractClause[]; unresolvedOverlaps: string[]; pendingReview: number };
const compare = (left: string, right: string) => {
  const a = left.split('\n').slice(0, 500), b = right.split('\n').slice(0, 500);
  const matrix = Array.from({ length: a.length + 1 }, () => Array<number>(b.length + 1).fill(0));
  for (let i = a.length - 1; i >= 0; i--) for (let j = b.length - 1; j >= 0; j--) matrix[i][j] = a[i] === b[j] ? 1 + matrix[i + 1][j + 1] : Math.max(matrix[i + 1][j], matrix[i][j + 1]);
  const leftChanged = new Set(a.map((_, index) => index)), rightChanged = new Set(b.map((_, index) => index));
  let i = 0, j = 0;
  while (i < a.length && j < b.length) { if (a[i] === b[j]) { leftChanged.delete(i); rightChanged.delete(j); i++; j++; } else if (matrix[i + 1][j] >= matrix[i][j + 1]) i++; else j++; }
  return { left: a.map((line, index) => ({ line, changed: leftChanged.has(index) })), right: b.map((line, index) => ({ line, changed: rightChanged.has(index) })) };
};

export function ContractReviewWorkspace({ contract }: { contract: Contract }) {
  const { addReviewComment, resolveReviewComment, supersedeClause } = useContracts();
  const [currentTerms, setCurrentTerms] = useState<CurrentTerms | null>(null);
  const [target, setTarget] = useState('GENERAL:');
  const [commentText, setCommentText] = useState('');
  const [resolutions, setResolutions] = useState<Record<string, string>>({});
  const [supersession, setSupersession] = useState<Record<string, { priorId: string; rationale: string }>>({});
  const [leftVersion, setLeftVersion] = useState(contract.draftVersions[0]?.id || '');
  const [rightVersion, setRightVersion] = useState(contract.draftVersions.at(-1)?.id || '');
  const [changeDocumentId, setChangeDocumentId] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/contracts/${contract.id}/current-terms`).then(response => response.ok ? response.json() : Promise.reject()).then(setCurrentTerms).catch(() => setCurrentTerms(null)); }, [contract]);
  const versions = useMemo(() => compare(contract.draftVersions.find(item => item.id === leftVersion)?.content || '', contract.draftVersions.find(item => item.id === rightVersion)?.content || ''), [contract.draftVersions, leftVersion, rightVersion]);
  const changes = contract.documents.filter(document => document.proposedChanges);
  const selectedChange = changes.find(item => item.id === changeDocumentId) || changes[0];
  const act = async (operation: () => Promise<unknown>, message: string) => { setBusy(true); try { await operation(); toast.success(message); } catch (error) { toast.error(error instanceof Error ? error.message : 'Review action failed.'); } finally { setBusy(false); } };
  return <div className="space-y-6">
    <section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="font-bold text-blue-950">Consolidated current terms</h2><p className="mt-1 text-xs text-slate-500">Only confirmed clauses from the authoritative signed contract or accepted lifecycle documents appear here. A replacement becomes current only after a reviewer records the supersession decision.</p>{currentTerms?.unresolvedOverlaps.length ? <p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">Possible unresolved overlapping clause numbers: {currentTerms.unresolvedOverlaps.join(', ')}. Review whether an amendment supersedes the earlier term.</p> : null}{currentTerms?.pendingReview ? <p className="mt-2 text-xs text-amber-700">{currentTerms.pendingReview} clause(s) still need human confirmation.</p> : null}<div className="mt-4 space-y-2">{currentTerms?.clauses.map(clause => <div key={clause.id} className="rounded-lg border p-3"><div className="text-sm font-bold">{clause.clauseNumber} · {clause.heading}</div><p className="mt-1 whitespace-pre-wrap text-xs text-slate-700">{clause.sourceText}</p><div className="mt-1 text-xs text-slate-400">{clause.sourceReference}{clause.sourceDocumentId ? ` · ${contract.documents.find(item => item.id === clause.sourceDocumentId)?.fileName || 'Source document'}` : ' · Manual clause'}</div></div>)}{!currentTerms?.clauses.length && <div className="text-sm text-slate-500">No confirmed current terms yet.</div>}</div></section>
    <section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="font-bold text-blue-950">Resolve amendment supersession</h2><p className="mt-1 text-xs text-slate-500">An accepted addendum does not silently erase an older clause or obligation. Select the specific earlier clause it replaces, and record the rationale.</p><div className="mt-4 space-y-3">{contract.clauses.filter(clause => clause.sourceDocumentId && contract.documents.some(document => document.id === clause.sourceDocumentId && document.changeReviewStatus === 'ACCEPTED') && !clause.supersedesClauseId).map(clause => { const value = supersession[clause.id] || { priorId: '', rationale: '' }; return <div key={clause.id} className="rounded-lg border p-3"><div className="text-sm font-bold">New clause {clause.clauseNumber} · {clause.heading}</div><div className="mt-1 text-xs text-slate-500">{clause.reviewStatus} · {clause.sourceText.slice(0, 250)}</div><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><select className={field} value={value.priorId} onChange={event => setSupersession(current => ({ ...current, [clause.id]: { ...value, priorId: event.target.value } }))}><option value="">Select earlier clause</option>{contract.clauses.filter(prior => prior.id !== clause.id && !prior.supersededByClauseId && prior.sourceDocumentId !== clause.sourceDocumentId).map(prior => <option key={prior.id} value={prior.id}>{prior.clauseNumber} · {prior.heading}</option>)}</select><input className={field} value={value.rationale} onChange={event => setSupersession(current => ({ ...current, [clause.id]: { ...value, rationale: event.target.value } }))} placeholder="Why this clause replaces the earlier term" /><button disabled={busy || clause.reviewStatus !== 'CONFIRMED' || !value.priorId || !value.rationale.trim()} onClick={() => act(() => supersedeClause(contract.id, clause.id, value.priorId, value.rationale), 'Supersession recorded; earlier obligations remain visible.')} className="rounded-lg bg-blue-800 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Record replacement</button></div></div>; })}{!contract.clauses.some(clause => clause.sourceDocumentId && contract.documents.some(document => document.id === clause.sourceDocumentId && document.changeReviewStatus === 'ACCEPTED') && !clause.supersedesClauseId) && <div className="text-sm text-slate-500">No accepted amendment clauses awaiting supersession.</div>}</div></section>
    {!!changes.length && <section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="font-bold text-blue-950">Amendment comparison</h2><select className={`${field} mt-3`} value={selectedChange?.id || ''} onChange={event => setChangeDocumentId(event.target.value)}>{changes.map(document => <option key={document.id} value={document.id}>{document.fileName} · {document.changeReviewStatus}</option>)}</select><div className="mt-4 space-y-3">{selectedChange?.proposedChanges?.clauses.map((clause, index) => { const earlier = contract.clauses.find(item => item.clauseNumber === clause.clauseNumber && item.sourceDocumentId !== selectedChange.id); return <div key={`${clause.clauseNumber}-${index}`} className="grid gap-3 md:grid-cols-2"><div className="rounded-lg border bg-slate-50 p-3"><div className="text-xs font-bold">Earlier · {earlier?.clauseNumber || 'Not found'}</div><p className="mt-2 whitespace-pre-wrap text-xs">{earlier?.sourceText || 'New clause; no matching number.'}</p></div><div className="rounded-lg border border-blue-200 bg-blue-50/40 p-3"><div className="text-xs font-bold text-blue-800">Proposed · {clause.clauseNumber}</div><p className="mt-2 whitespace-pre-wrap text-xs">{clause.sourceText}</p></div></div>; })}</div></section>}
    {contract.draftVersions.length > 1 && <section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="font-bold text-blue-950">Draft version comparison</h2><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className={field} value={leftVersion} onChange={event => setLeftVersion(event.target.value)}>{contract.draftVersions.map(version => <option key={version.id} value={version.id}>Earlier v{version.version} · {version.changeSummary}</option>)}</select><select className={field} value={rightVersion} onChange={event => setRightVersion(event.target.value)}>{contract.draftVersions.map(version => <option key={version.id} value={version.id}>Later v{version.version} · {version.changeSummary}</option>)}</select></div><div className="mt-3 grid gap-3 md:grid-cols-2">{[versions.left, versions.right].map((lines, index) => <div key={index} className="max-h-96 overflow-auto rounded-lg border bg-slate-50 p-3 font-mono text-xs">{lines.map((item, line) => <div key={line} className={`min-h-4 whitespace-pre-wrap ${item.changed ? index ? 'bg-green-100' : 'bg-red-100' : ''}`}>{item.line || ' '}</div>)}</div>)}</div><p className="mt-2 text-xs text-slate-500">Changed lines are highlighted; Legal must still review the actual Word/PDF wording and signatures.</p></section>}
    <section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><h2 className="font-bold text-blue-950">Collaborative review comments</h2><div className="mt-3 grid gap-2 sm:grid-cols-[220px_1fr_auto]"><select className={field} value={target} onChange={event => setTarget(event.target.value)}><option value="GENERAL:">General</option>{contract.clauses.map(clause => <option key={clause.id} value={`CLAUSE:${clause.id}`}>Clause {clause.clauseNumber} · {clause.heading}</option>)}{contract.documents.map(document => <option key={document.id} value={`DOCUMENT:${document.id}`}>File · {document.fileName}</option>)}{contract.draftVersions.map(version => <option key={version.id} value={`DRAFT:${version.id}`}>Draft v{version.version}</option>)}</select><input className={field} value={commentText} onChange={event => setCommentText(event.target.value)} placeholder="Question, issue or suggested change" /><button disabled={busy || !commentText.trim()} onClick={() => act(async () => { const [targetType, targetId] = target.split(':'); await addReviewComment(contract.id, targetType as 'GENERAL' | 'CLAUSE' | 'DOCUMENT' | 'DRAFT', targetId || '', commentText); setCommentText(''); }, 'Review comment added.')} className="rounded-lg bg-blue-800 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Comment</button></div><div className="mt-4 space-y-3">{(contract.comments || []).slice().reverse().map(comment => <div key={comment.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><div className="text-xs font-bold">{comment.targetType} · {comment.author} · {new Date(comment.createdAt).toLocaleString()}</div><span className="text-xs">{comment.status}</span></div><p className="mt-2 text-sm">{comment.text}</p>{comment.status === 'RESOLVED' ? <div className="mt-2 text-xs text-green-700">Resolved by {comment.resolvedBy}: {comment.resolution}</div> : <div className="mt-2 flex gap-2"><input className={field} value={resolutions[comment.id] || ''} onChange={event => setResolutions(current => ({ ...current, [comment.id]: event.target.value }))} placeholder="Resolution or accepted action" /><button disabled={busy || !resolutions[comment.id]?.trim()} onClick={() => act(() => resolveReviewComment(contract.id, comment.id, resolutions[comment.id]), 'Comment resolved.')} className="rounded-lg bg-green-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Resolve</button></div>}</div>)}{!contract.comments?.length && <div className="text-sm text-slate-500">No review comments yet.</div>}</div></section>
  </div>;
}
