import { useState } from 'react';
import { toast } from 'sonner';
import type { Vendor, VendorSiteMobilisation } from '../vendorTypes';
import { useContracts } from '../context/ContractContext';
import { useVendors } from '../context/VendorContext';

const field = 'w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';

export function VendorSites({ vendor }: { vendor: Vendor }) {
  const { entities } = useContracts();
  const { addPersonnel, updatePersonnel, createSiteMobilisation, updateSiteMobilisation, decideSiteMobilisation } = useVendors();
  const [siteName, setSiteName] = useState('');
  const [worker, setWorker] = useState({ name: '', role: '', siteAssignment: '' });
  const [edits, setEdits] = useState<Record<string, Pick<VendorSiteMobilisation, 'personnelIds' | 'inductionDocumentIds'>>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const sites = entities.find(entity => entity.id === vendor.entityId)?.sites || [];
  const run = async (action: () => Promise<void>, message: string) => { setBusy(true); try { await action(); toast.success(message); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save.'); } finally { setBusy(false); } };
  const addWorker = () => run(async () => { await addPersonnel(vendor.id, worker); setWorker({ name: '', role: '', siteAssignment: '' }); }, 'Worker added. Run compliance checks before site approval.');
  const edit = (site: VendorSiteMobilisation) => edits[site.id] || { personnelIds: site.personnelIds, inductionDocumentIds: site.inductionDocumentIds };
  const change = (site: VendorSiteMobilisation, value: Pick<VendorSiteMobilisation, 'personnelIds' | 'inductionDocumentIds'>) => setEdits(current => ({ ...current, [site.id]: value }));
  return <section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm">
    <h2 className="font-bold text-blue-950">Site mobilisation and named roster</h2>
    <p className="mt-1 text-xs leading-5 text-slate-500">Company approval does not approve individual workers. Each site needs its own roster, passed competency checks, reviewed induction evidence and a human decision. Changing the roster restarts review.</p>
    <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto]"><select className={field} value={siteName} onChange={event => setSiteName(event.target.value)}><option value="">Choose an entity site</option>{sites.map(site => <option key={site} value={site}>{site}</option>)}</select><button disabled={busy || !siteName} onClick={() => run(() => createSiteMobilisation(vendor.id, siteName, vendor.personnel.filter(person => person.status === 'ACTIVE' && person.siteAssignment === siteName).map(person => person.id)), 'Site case created.')} className="rounded-lg bg-blue-800 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Start site review</button></div>
    <div className="mt-4 space-y-4">{(vendor.siteMobilisations || []).map(site => {
      const current = edit(site);
      return <div key={site.id} className="rounded-xl border border-slate-200 p-4">
        <div className="flex flex-wrap items-center justify-between gap-2"><div className="font-bold">{site.siteName}</div><span className={`rounded-full px-2 py-1 text-xs font-bold ${site.readinessStatus === 'APPROVED' ? 'bg-green-50 text-green-700' : site.readinessStatus === 'BLOCKED' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}>{site.readinessStatus?.replaceAll('_', ' ') || 'PENDING'}</span></div>
        {!!site.readinessReasons?.length && <ul className="mt-2 list-inside list-disc text-xs text-red-700">{site.readinessReasons.map(reason => <li key={reason}>{reason}</li>)}</ul>}
        <div className="mt-3 grid gap-3 md:grid-cols-2">{vendor.personnel.map(person => <div key={person.id} className="rounded-lg bg-slate-50 p-3"><label className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={current.personnelIds.includes(person.id)} onChange={event => change(site, { ...current, personnelIds: event.target.checked ? [...current.personnelIds, person.id] : current.personnelIds.filter(id => id !== person.id) })} /><span><strong>{person.name}</strong><small className="block text-slate-500">{person.role} · {person.siteAssignment || 'Site unassigned'}</small></span></label>{current.personnelIds.includes(person.id) && <select className={`${field} mt-2`} value={current.inductionDocumentIds[person.id] || ''} onChange={event => change(site, { ...current, inductionDocumentIds: { ...current.inductionDocumentIds, [person.id]: event.target.value } })}><option value="">Select reviewed induction evidence</option>{vendor.documents.filter(document => document.subjectId === person.id && document.documentType === 'SITE_INDUCTION').map(document => <option key={document.id} value={document.id}>{document.fileName} · {document.extractionStatus}</option>)}</select>}</div>)}</div>
        <div className="mt-3 flex justify-end"><button disabled={busy} onClick={() => run(() => updateSiteMobilisation(vendor.id, site.id, current), 'Roster and induction links saved; a new decision is required.')} className="rounded-lg border border-blue-200 px-3 py-2 text-xs font-bold text-blue-800">Save roster and evidence</button></div>
        <div className="mt-3 grid gap-2 border-t pt-3 sm:grid-cols-[1fr_auto_auto]"><input className={field} value={notes[site.id] || ''} onChange={event => setNotes(currentNotes => ({ ...currentNotes, [site.id]: event.target.value }))} placeholder="Reviewer rationale" /><button disabled={busy || site.readinessStatus !== 'READY_FOR_APPROVAL'} onClick={() => run(() => decideSiteMobilisation(vendor.id, site.id, 'APPROVED', notes[site.id] || ''), 'Named roster approved for this site.')} className="rounded-lg bg-green-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Approve site</button><button disabled={busy} onClick={() => run(() => decideSiteMobilisation(vendor.id, site.id, 'REJECTED', notes[site.id] || ''), 'Site mobilisation rejected.')} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700 disabled:opacity-40">Reject</button></div>
        {site.decisionActor && <div className="mt-2 text-xs text-slate-500">Latest decision: {site.decision} by {site.decisionActor} · {site.decisionNotes}</div>}
      </div>;
    })}{!vendor.siteMobilisations?.length && <div className="rounded-lg border border-dashed p-5 text-sm text-slate-500">No site mobilisation cases yet.</div>}</div>
    <div className="mt-5 border-t pt-4"><h3 className="text-sm font-bold">Maintain vendor workers</h3><div className="mt-2 space-y-2">{vendor.personnel.map(person => <div key={person.id} className="flex flex-wrap items-center gap-2 rounded-lg bg-slate-50 p-2 text-xs"><span className="flex-1 font-bold">{person.name} · {person.role} · {person.siteAssignment || 'No site'} · {person.status}</span><button disabled={busy} onClick={() => run(() => updatePersonnel(vendor.id, person.id, { status: person.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE' }), 'Worker status updated; site clearance requires review.')} className="font-bold text-blue-700">{person.status === 'ACTIVE' ? 'Deactivate' : 'Reactivate'}</button></div>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_1fr_auto]"><input className={field} value={worker.name} onChange={event => setWorker({ ...worker, name: event.target.value })} placeholder="Worker name" /><input className={field} value={worker.role} onChange={event => setWorker({ ...worker, role: event.target.value })} placeholder="Role / trade" /><select className={field} value={worker.siteAssignment} onChange={event => setWorker({ ...worker, siteAssignment: event.target.value })}><option value="">Select site</option>{sites.map(site => <option key={site} value={site}>{site}</option>)}</select><button disabled={busy || !worker.name || !worker.role} onClick={addWorker} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-800 disabled:opacity-40">Add worker</button></div></div>
  </section>;
}
