import { useState } from 'react';
import { ShieldAlert } from 'lucide-react';
import { toast } from 'sonner';
import type { Vendor, VendorRiskCase } from '../vendorTypes';
import { useVendors } from '../context/VendorContext';
import { useAuth } from '../context/AuthContext';

const inputClass = 'w-full rounded-lg border border-slate-200 px-3 py-2 text-sm';
const categories: VendorRiskCase['category'][] = ['LEGAL_ADVERSE', 'FINANCIAL', 'CONFLICT_OF_INTEREST', 'SAFETY', 'INSURANCE', 'BLACKLIST', 'OTHER'];
const request = async (url: string, body: unknown) => { const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Risk decision could not be saved.'); return data; };

export function VendorRiskCases({ vendor }: { vendor: Vendor }) {
  const { refresh } = useVendors();
  const { user } = useAuth();
  const canDecide = user?.role === 'GROUP_ADMIN' || user?.role === 'ENTITY_ADMIN';
  const [form, setForm] = useState({ category: 'LEGAL_ADVERSE' as VendorRiskCase['category'], severity: 'HIGH' as VendorRiskCase['severity'], title: '', findings: '', ownerEmail: '', dueDate: '', sourceVerificationIds: [] as string[], sourceDocumentIds: [] as string[], sourceEventIds: [] as string[] });
  const [decisions, setDecisions] = useState<Record<string, { decision: 'MITIGATED' | 'DISMISSED'; reason: string }>>({});
  const [busy, setBusy] = useState(false);
  const toggle = (key: 'sourceVerificationIds' | 'sourceDocumentIds' | 'sourceEventIds', id: string) => setForm(current => ({ ...current, [key]: current[key].includes(id) ? current[key].filter(item => item !== id) : [...current[key], id] }));
  const create = async () => { setBusy(true); try { await request(`/api/vendors/${vendor.id}/risk-cases`, form); await refresh(); setForm({ category: 'LEGAL_ADVERSE', severity: 'HIGH', title: '', findings: '', ownerEmail: '', dueDate: '', sourceVerificationIds: [], sourceDocumentIds: [], sourceEventIds: [] }); toast.success('Source-linked risk case opened and assigned for follow-up.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not open risk case.'); } finally { setBusy(false); } };
  const decide = async (id: string) => { const entry = decisions[id]; if (!entry?.reason.trim()) return; setBusy(true); try { await request(`/api/vendors/${vendor.id}/risk-cases/${id}/decision`, entry); await refresh(); toast.success('Risk decision recorded in the audit trail.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not decide risk case.'); } finally { setBusy(false); } };
  return <section className="rounded-xl border border-gray-100 bg-white p-5 shadow-sm">
    <div className="flex items-center gap-2 font-bold text-blue-950"><ShieldAlert className="h-5 w-5" />Risk cases and decisions</div>
    <p className="mt-1 text-xs text-slate-500">Link an adverse check, document or measured incident. Open high/critical cases block a new approval and site mobilisation; an earlier approval is not silently revoked.</p>
    <div className="mt-4 space-y-3">{(vendor.riskCases || []).map(item => { const decision = decisions[item.id] || { decision: 'MITIGATED' as const, reason: '' }; return <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{item.title}</strong><span className={item.status === 'OPEN' && ['HIGH', 'CRITICAL'].includes(item.severity) ? 'font-bold text-red-700' : 'text-slate-500'}>{item.severity} · {item.status}</span></div><p className="mt-2 text-slate-700">{item.findings}</p><div className="mt-2 text-xs text-slate-500">{item.category.replaceAll('_', ' ')} · Due {item.dueDate} · Owner {item.ownerEmail} · {item.sourceVerificationIds.length + item.sourceDocumentIds.length + item.sourceEventIds.length} linked source(s)</div><div className="mt-2 flex flex-wrap gap-2">{item.sourceVerificationIds.map(id => { const check = vendor.verifications.find(value => value.id === id); return <span key={id} className="rounded bg-amber-50 px-2 py-1 text-xs">Check: {check?.authority || 'Verification'} {check?.citations[0] && <a className="font-bold text-blue-700 underline" href={check.citations[0].url} target="_blank" rel="noreferrer">Source</a>}</span>; })}{item.sourceDocumentIds.map(id => { const document = vendor.documents.find(value => value.id === id); return <a key={id} className="rounded bg-indigo-50 px-2 py-1 text-xs font-bold text-blue-700 underline" href={`/api/vendors/${vendor.id}/documents/${id}/download`}>{document?.fileName || 'Document'}</a>; })}{item.sourceEventIds.map(id => <span key={id} className="rounded bg-slate-100 px-2 py-1 text-xs">Event: {vendor.performanceEvents?.find(value => value.id === id)?.title || id}</span>)}</div>{item.status === 'OPEN' && canDecide ? <div className="mt-3 grid gap-2 border-t pt-3 sm:grid-cols-[150px_1fr_auto]"><select className={inputClass} value={decision.decision} onChange={event => setDecisions(current => ({ ...current, [item.id]: { ...decision, decision: event.target.value as typeof decision.decision } }))}><option value="MITIGATED">Mitigated</option><option value="DISMISSED">Dismissed</option></select><input className={inputClass} value={decision.reason} onChange={event => setDecisions(current => ({ ...current, [item.id]: { ...decision, reason: event.target.value } }))} placeholder="Decision rationale and evidence *" /><button disabled={busy || !decision.reason.trim()} onClick={() => void decide(item.id)} className="rounded-lg bg-blue-800 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Record decision</button></div> : item.status !== 'OPEN' ? <div className="mt-2 text-xs text-green-700">{item.decidedBy}: {item.decisionReason}</div> : null}</div>; })}{!vendor.riskCases?.length && <div className="rounded-lg border border-dashed p-4 text-sm text-slate-500">No source-linked risk cases.</div>}</div>
    {canDecide && <div className="mt-5 grid gap-3 border-t pt-4 sm:grid-cols-2"><label className="text-xs font-bold">Risk category<select className={`${inputClass} mt-1`} value={form.category} onChange={event => setForm({ ...form, category: event.target.value as VendorRiskCase['category'] })}>{categories.map(item => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></label><label className="text-xs font-bold">Severity<select className={`${inputClass} mt-1`} value={form.severity} onChange={event => setForm({ ...form, severity: event.target.value as VendorRiskCase['severity'] })}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label className="text-xs font-bold sm:col-span-2">Finding title<input className={`${inputClass} mt-1`} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></label><label className="text-xs font-bold sm:col-span-2">Findings and review context<textarea className={`${inputClass} mt-1`} rows={2} value={form.findings} onChange={event => setForm({ ...form, findings: event.target.value })} /></label><label className="text-xs font-bold">Follow-up owner email<input type="email" className={`${inputClass} mt-1`} value={form.ownerEmail} onChange={event => setForm({ ...form, ownerEmail: event.target.value })} placeholder="Defaults to your email" /></label><label className="text-xs font-bold">Follow-up due date<input type="date" className={`${inputClass} mt-1`} value={form.dueDate} onChange={event => setForm({ ...form, dueDate: event.target.value })} /></label><div className="sm:col-span-2"><div className="text-xs font-bold">Link source evidence (at least one)</div><div className="mt-2 flex flex-wrap gap-3">{vendor.verifications.map(item => <label key={item.id} className="text-xs"><input type="checkbox" checked={form.sourceVerificationIds.includes(item.id)} onChange={() => toggle('sourceVerificationIds', item.id)} /> {item.authority} · {item.status}</label>)}{vendor.documents.map(item => <label key={item.id} className="text-xs"><input type="checkbox" checked={form.sourceDocumentIds.includes(item.id)} onChange={() => toggle('sourceDocumentIds', item.id)} /> {item.fileName}</label>)}{(vendor.performanceEvents || []).map(item => <label key={item.id} className="text-xs"><input type="checkbox" checked={form.sourceEventIds.includes(item.id)} onChange={() => toggle('sourceEventIds', item.id)} /> {item.title}</label>)}</div></div><button disabled={busy || !form.title.trim() || !form.findings.trim() || !form.sourceVerificationIds.length && !form.sourceDocumentIds.length && !form.sourceEventIds.length} onClick={() => void create()} className="rounded-lg bg-blue-800 px-4 py-2 text-xs font-bold text-white disabled:opacity-50 sm:col-span-2">Open risk case and assign follow-up</button></div>}
  </section>;
}
